accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>', views.UserProfileView.as_view(), name ='profile'),
    path('follow/<int:user_id>', views.FollowUserView.as_view(), name='follow'),
    path('unfollow/<int:user_id>', views.UnfollowUserView.as_view(), name='unfollow'),
    path('followers/<int:user_id>', views.UserGetFollowersView.as_view(), name='get_followers'),
    path('followings/<int:user_id>', views.UserGetFollowingsView.as_view(), name='get_followings'),
    path('edit_user', views.EditProfileView.as_view(), name='edit_user')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('detail/<int:post_id>', views.PostDetailView.as_view(), name='detail'),
    path('edit/<int:post_id>', views.PostEditView.as_view(), name='edit'),
    path('create/', views.CreatePostView.as_view(), name='create'),
    path('bid/<int:post_id>', views.TakeBidView.as_view(), name='bid'),
    path('like/<int:post_id>', views.PostLikeView.as_view(), name='like'),
    path('delete/<int:post_id>', views.PostDeleteView.as_view(), name='delete'),
    path('reply/<int:post_id>/<int:comment_id>', views.AddReplyCommentView.as_view(), name='reply'),
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User 
from django.urls import reverse 



class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_posts")
    title = models.CharField(max_length=20)
    current_price = models.DecimalField(decimal_places=2, max_digits=8, default='0.00')
    starting_bid = models.DecimalField(decimal_places=2, max_digits=8, default='0.00')
    description = models.TextField()
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name="Post_categories")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    
    class Meta:
        ordering = ('-title',)
    
    def __str__(self):
        return f"{self.title}"
    
    def like_count(self):
        return self.post_liked.count()
    
    def user_can_like(self, user):
        user_like = user.liker.filter(post=self)
        if user_like.exists():
            return False
        return True
    
    def get_absolute_url(self):
        return reverse("shop:detail", args=(self.id,))
    
    
class Bids(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None, related_name='posts_bid')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    amount = models.DecimalField(decimal_places=2, max_digits=8, default=None)
    
    def __str__(self):
        return f"{self.user} bids on {self.post}, {self.amount}$"
    
    
class Category(models.Model):
    subject = models.CharField(max_length=20)
    
    def __str__(self):
        return f"{self.subject}"
    

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_liked')
    
    def __str__(self):
        return f"{self.user} liked {self.post}"
    
    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomments')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='replies', blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    body = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user} commented on {self.post}"
    

shop/forms.py
from django import forms 
from django.contrib.auth.models import User
from .models import Post, Bids, Comment


class PostEditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'description', 'category')
        

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'description', 'category', 'starting_bid')
        
        
class BidForm(forms.ModelForm):
    class Meta:
        model = Bids 
        fields = ('amount',)
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        
class AddCommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        labels = {
            'body': 'your reply'
        }
        
class SearchForm(forms.Form):
    search = forms.CharField(label='search')
    

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.models import User
from .models import Post, Bids, Category, Like, Comment
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostEditForm, CreatePostForm, BidForm, CommentForm, AddCommentReplyForm, SearchForm
from django.contrib import messages
from django.urls import reverse 
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class HomePageView(View):
    form_class = SearchForm
     
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        if request.GET.get('search'):
            posts = posts.filter(title__contains=request.GET['search'])
        return render(request, 'shop/home.html', {
            "posts": posts,
            "form": self.form_class
        })
        

class PostDetailView(View):
    form_class = CommentForm
    form_class_reply = AddCommentReplyForm
    
    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'])
        self.comments = self.post_instance.pcomments.filter(is_reply=False)
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        can_like = False
        if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            can_like = True
        return render(request, 'shop/detial.html', {
            "post": self.post_instance,
            "comments": self.comments,
            "form": self.form_class ,
            "reply_form": self.form_class_reply,
            "can_like": can_like,
        })
        
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request, "Your comment submitted successfully", "success")
        return redirect('shop:detail', self.post_instance.id)
        
        
class PostEditView(LoginRequiredMixin, View):
    form_class = PostEditForm
    
    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)
    
    
    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if not post.user.id == request.user.id:
            messages.error(request, "Just the owner can edit this post", "danger")
            return redirect("shop:home")
        return super().dispatch(request, *args, **kwargs)
    
    
    def get(self, request, *args, **kwargs):
        form = self.form_class(instance=self.post_instance)
        return render(request, 'shop/edit_post.html', {
            "form": form 
        })
        
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, instance=self.post_instance)
        if form.is_valid():
            form.save()
        return redirect("shop:detail", self.post_instance.id)
            
    
    
class CreatePostView(LoginRequiredMixin, View):
    form_class = CreatePostForm
    
    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, 'shop/create_post.html', {
            "form": form
        })
        
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.save()
        return redirect("shop:home")
    

class TakeBidView(LoginRequiredMixin, View):
    form_class = BidForm
    
    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, 'shop/new_bid.html', {
            "form": form
        })
        
        
    def post(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data['amount']
            if cd >= post.current_price:
                post.current_price = cd
                post.owner = request.user
                post.save()
        return redirect('shop:detail', post.id)
    
    
class PostLikeView(LoginRequiredMixin, View):
    
    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=kwargs['post_id'])
        like = Like.objects.filter(user=request.user, post=post)
        if like.exists():
            messages.error(request, 'you have already liked this post', 'danger')
        else:
            Like.objects.create(user=request.user, post=post)
            messages.success(request, 'You like this post', 'success')
        return redirect('shop:detail', post.id)
    
    
class PostDeleteView(LoginRequiredMixin, View):
    
    def get(self, request, post_id):
        post_instance = Post.objects.get(id=post_id)
        if request.user.id == post_instance.user.id :
            post_instance.delete()
            messages.success(request, 'You deleted this post successfully', 'success')
        else:
            messages.error(request, 'You can not delete this post', 'danger')
        return redirect('shop:home')


class AddReplyCommentView(LoginRequiredMixin, View):
    form_class = AddCommentReplyForm
    
    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=kwargs['post_id'])
        comment = get_object_or_404(Comment, pk=kwargs['comment_id'])
        form = self.form_class(request.POST)
        if form.is_valid():
            new_reply = form.save(commit=False)
            new_reply.user = request.user
            new_reply.post = post
            new_reply.reply = comment
            new_reply.is_reply = True 
            new_reply.save()
            messages.success(request, 'Your comment submitted successfully', 'success')
        return redirect('shop:detail', post.id)

shop/templates/shop/create_post.html
{% extends 'base.html' %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_div }}
        <input type="submit" value="Create">
    </form>


{% endblock %}

shop/templates/shop/detial.html
{% extends 'base.html' %}

{% block content %}

{% if request.user.id == post.user.id %} 
    <a href="{% url 'shop:delete' post.id %}" class="btn btn-danger">Delete</a>
{% endif %} 


{% if request.user.id == post.user.id %}
    <a href="{% url 'shop:edit' post.id %}" class="btn btn-primary">Edit</a><br/>
{% endif %}


from: <a href="{% url 'accounts:profile' post.user.id %}" class="btn btn-primary">{{ post.user }}</a><hr/>

title: {{ post.title }}<br/>
info: {{ post.description}}<br/>
category: {{ post.category}}<br/>
price: {{ post.current_price }}<br/>
owner until now: {{ post.owner }}<hr/>

<a href="{% url 'shop:like' post.id %}" class="{% if not can_like %}disabled {% endif %} btn btn-primary">Like {{ post.like_count }}</a>
<hr/>
do you wanna be the owner? commit a new bid :D 
<a href="{% url 'shop:bid' post.id %}" class="btn btn-info">Commit a new bid</a>
<hr/>

{% if request.user.is_authenticated %}

    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_div }}<br/>
    <input type="submit" value="Send">
    </form><br/>

{% else %}
    <p>only logged in users can comment</p>
{% endif %}

{% for comment in comments %}
<div class="card bg-dark text-white">
    <p class="card-header">{{ comment.user }} | {{ comment.created|timesince }}</p>
    <p class="card-body">{{ comment.body }}</p>

        {% if request.user.is_authenticated %}
            <form action="{% url 'shop:reply' post.id comment.id %}" method="post">
                {% csrf_token %}
                {{ reply_form.as_div }}
                <input type="submit" value="add">
            </form>
        {% endif %}

        {% with replies=comment.replies.all %}
        {% for reply in replies %}
                <p class="bg-primary p-3 m-2">{{ reply.user}} <br/> {{ reply.body }}</p>
        {% endfor %}
        {% endwith %}

</div><br/>
{% empty %}
    <p>NO comments yet!</p>
{% endfor %}

{% endblock %}

shop/templates/shop/edit_post.html
{% extends 'base.html' %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_div }}
        <input type="submit" value="save changes">
    </form>

{% endblock %}

shop/templates/shop/home.html
{% extends 'base.html' %}

{% block content %}

    <form action="" method="get">
        {{ form.as_p }}
        <input type="submit" value="Search">
    </form>


    <br/> <br/>
    {% if request.user.is_authenticated %}
        <a href="{% url 'shop:create' %}" class="btn btn-primary">New Post</a>
    {% endif %}


    <br/> <br/>
    <div class="card">
    {% for post in posts %} 
        <a href="{{ post.get_absolute_url }}" class="card-body">{{ post.title }}</a>
    {% endfor %}
    </div>

{% endblock %}

shop/templates/shop/new_bid.html
{% extends 'base.html' %}

{% block content%}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="offer">
    </form>


{% endblock %}