accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>', views.UserProfileView.as_view(), name ='profile'),
    path('follow/<int:user_id>', views.FollowUserView.as_view(), name='follow'),
    path('unfollow/<int:user_id>', views.UnfollowUserView.as_view(), name='unfollow'),
    path('followers/<int:user_id>', views.UserGetFollowersView.as_view(), name='get_followers'),
    path('followings/<int:user_id>', views.UserGetFollowingsView.as_view(), name='get_followings'),
    path('edit_user', views.EditProfileView.as_view(), name='edit_user')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('detail/<int:post_id>', views.PostDetailView.as_view(), name='detail'),
    path('edit/<int:post_id>', views.PostEditView.as_view(), name='edit'),
    path('create/', views.CreatePostView.as_view(), name='create'),
    path('bid/<int:post_id>', views.TakeBidView.as_view(), name='bid'),
    path('like/<int:post_id>', views.PostLikeView.as_view(), name='like'),
    path('delete/<int:post_id>', views.PostDeleteView.as_view(), name='delete'),
    path('reply/<int:post_id>/<int:comment_id>', views.AddReplyCommentView.as_view(), name='reply'),
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }} col-md-2">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <div class="navbar-nav">

        {% if request.user.is_authenticated %}
            <a class="nav-link active" href="{% url 'accounts:profile' request.user.id %}">{{request.user.username}}</a>
        {% endif %}

        <a class="nav-link active" href="{% url 'shop:home' %}">Home</a>

        {% if request.user.is_authenticated %}
            <a class="nav-link active" href="{% url 'accounts:user_logout' %}">Logout</a>
        {% else %}
            <a class="nav-link active" href="{% url 'accounts:user_register' %}">Register</a>
            <a class="nav-link active" href="{% url 'accounts:user_login' %}">Login</a>
        {% endif %}
        
      </div>
    </div>
  </nav>